import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";

import { CartProvider } from "~/contexts/CartProvider";
import { TRPCReactProvider } from "~/trpc/react";

import Navbar from "~/components/Navbar";
import Footer from "~/components/Footer";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>
        <ClerkProvider dynamic>
          <TRPCReactProvider>
            <CartProvider>
              <Navbar />
              <main className="container mx-auto px-4 py-6 min-h-[70vh]">{children}</main>
              <Footer />
            </CartProvider>
          </TRPCReactProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
